### ISSUE TITLE
#define MAX_DATA_LEN 65536 is hardcoded

### ISSUE THREAD

**Issue by pschatzmann** [pschatzmann/SIDPlayer#3]
We should provide the functionality the setMaxDataLength(int) method where we can define this dynamically. This way we can also support processors which do not have a huge RAM available.

The SIDPlayer should skip files which are exceeding the actual limit.

**Comment by beachviking** [comment]
I had a look at the libcsid code and the issue is that this number is used to define the memory space for the emulated 6502 environment.  The psid files will contain 6510 asm instructions to manipulate this memory as needed, assuming a full Commodore 64 memory map. Check out the function CPU() libcsid.cpp. The number is hardcoded to represent and allocate the 16 bit memory space found on a Commdore 64. Doubt this can be altered without impacting certain SID tunes negatively.

**Comment by pschatzmann** [comment]
bad luck
